[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin/=lib/openzeppelin-contracts/']
vme_version = 'london'

[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"
saigon = "https://ronin-saigon.core.chainstack.com/46d251a9fa8567059b826862b7c21f20"

